from tkinter import *
from PIL import ImageTk,Image
from PIL import Image, ImageDraw, ImageFont

import random
import os
import datetime
from datetime import datetime
import qrcode
import tkinter.messagebox
import xlsxwriter
from openpyxl import load_workbook

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders

def handle_enter():
    receiver_email_id = mail_input.get()

    image = Image.new('RGB', (1100, 1500), (255, 255, 255))
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype('arial.ttf', size=45)

    myname = name_input.get()
    student_name = ("Name : " + myname)
    course = course_input.get()
    student_course = ("Course : " + course)
    phone = phone_input.get()
    student_phone = ("Phone : " + phone)
    mail = mail_input.get()
    student_mail = ("Mail : " + mail)
    enrollment = enrollment_input.get()
    student_enrollment = ("Enrollment Number : " + enrollment)
    event_name = event_input.get()

    # logo = "PCU-logo.png"

    #INTRO
    (x, y) = (270, 50)
    message = "Pimpri Chinchwad Education Trust's"
    name = message  
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=35)
    draw.text((x, y), name, fill=color, font=font)

    (x, y) = (100, 100)
    message = "PIMPRI CHINCHWAD UNIVERSITY"
    name = message
    color = '#900C3F'
    font = ImageFont.truetype('arial.ttf', size=55)
    draw.text((x, y), name, fill=color, font=font)

    (x, y) = (160, 170)
    message = "Plot No. 44, 49 50, Mohitewadi Rd, Mohitewadi, Maharashtra 412106"
    name = message
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=25)
    draw.text((x, y), name, fill=color, font=font)

    #EVENT NAME
    (x, y) = (50, 270)
    message = event_name
    name = message
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=50)
    draw.text((x, y), name, fill=color, font=font)

    # DETAILS : 
    #NAME : 
    (x, y) = (50, 400)
    message = student_name
    name = message
    color = 'rgb(0, 0, 0)'
    font = ImageFont.truetype('arial.ttf', size=45)
    draw.text((x, y), name, fill=color, font=font)

    #COURSENAME : 
    (x, y) = (50, 460)
    message = student_course
    name = message
    color = 'rgb(0, 0, 0)' 
    font = ImageFont.truetype('arial.ttf', size=45)
    draw.text((x, y), name, fill=color, font=font)

    #PHONE : 
    (x, y) = (50, 520)
    message = student_phone
    name = message
    color = 'rgb(0, 0, 0)'
    font = ImageFont.truetype('arial.ttf', size=45)
    draw.text((x, y), name, fill=color, font=font)

    #MAIL : 
    (x, y) = (50, 580)
    message = student_mail
    name = message
    color = 'rgb(0, 0, 0)' 
    font = ImageFont.truetype('arial.ttf', size=45)
    draw.text((x, y), name, fill=color, font=font)

    #ENROLLMENT NUMBER : 
    (x, y) = (50, 640)
    message = student_enrollment
    name = message
    color = 'rgb(0, 0, 0)' 
    font = ImageFont.truetype('arial.ttf', size=45)
    draw.text((x, y), name, fill=color, font=font)

    #LINE : 
    (x, y) = (80, 700)
    message = "------------------------------------------------------------------------------"
    name = message
    color = 'rgb(0, 0, 0)' 
    font = ImageFont.truetype('arial.ttf', size=35)
    draw.text((x, y), name, fill=color, font=font)

    #IDNUMBER
    (x, y) = (255, 800)
    idno = random.randint(191022001, 191022010)
    message = str("ID Number : " + str(idno))
    color = '#900C3F' 
    font = ImageFont.truetype('arial.ttf', size=55)
    draw.text((x, y), message, fill=color, font=font)

    #WARNING
    (x, y) = (190, 1350)
    message = "This is an autogenerated virtual and temporary ID card"
    name = message
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=30)
    draw.text((x, y), name, fill=color, font=font)

    (x, y) = (55, 1380)
    message = "Please note that this ID card is not an official university identification card"
    name = message
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=30)
    draw.text((x, y), name, fill=color, font=font)

    (x, y) = (250, 1410)
    message = "It should not be used for any official purposes"
    name = message
    color = '#4b4b4b'
    font = ImageFont.truetype('arial.ttf', size=30)
    draw.text((x, y), name, fill=color, font=font)

    # IMAGE SAVING : 

    image.save(str(myname) + '.png')

    #PCU LOGO : 

    img = qrcode.make(str(myname) + " : " + str(enrollment))  
    image = img.resize((500, 500))
    image.save(str(idno) + '.bmp')

    til = Image.open(myname + '.png')
    im = Image.open(str(idno) + '.bmp') 
    til.paste(im, (310, 850))

    til.save(myname + '.png')

    print(('\n\n\nYour ID Card Successfully created in a PNG file ' + myname + '.png'))

    #Generated ID : 
    Card = Image.open(myname + '.png')
    resized_Card = Card.resize((300, 394))
    Card = ImageTk.PhotoImage(resized_Card)
    Card_lable = Label(root,image = Card)
    Card_lable.place(x=1100,y=235)

    #Exel Sheet Data :
    event_name = str(event_input.get())
    current_datetime = datetime.now()

    File_name = (event_name + ".xlsx")
    file_path = File_name 
    wb = load_workbook(file_path)

    ws = wb.active
    # Data to append (line by line)
    data = [
        [myname, enrollment, mail, phone, course, current_datetime]
    ]

    # Append each row of data to the sheet
    for row in data:
        ws.append(row)

    # Save the workbook
    wb.save(file_path)

    print(f"Data has been successfully added to {file_path}.")

    # Email configuration
    smtp_server = 'smtp.gmail.com'
    smtp_port = 587 
    username = "sdhumal2905@gmail.com"
    password = 'gbloqkestalzoikt'
    to_email = mail
    subject = (event_name + " Registration")
    body = (f"Congratulations {myname} :\nYou have Sucessfully Registerd for {event_name} :\n \nPlease find attached to your Virtual ID Card :\nTHANK YOU")

    # Create a multipart email
    msg = MIMEMultipart()
    msg['From'] = username
    msg['To'] = to_email
    msg['Subject'] = subject

    # Attach the body with the email
    msg.attach(MIMEText(body, 'plain'))

    # ID = (myname + '.png')
    # Open the image file in binary mode
    ID = (myname + '.png')
    with open(ID, 'rb') as image_file:
        img = MIMEImage(image_file.read())
        img.add_header('Content-ID', '<image1>') 
        img.add_header('Content-Disposition', 'attachment; filename = "ID"')
        msg.attach(img)

    # Connect to the SMTP server and send the email
    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls() 
        server.login(username, password)
        server.send_message(msg)

    print("Email sent successfully!")
    tkinter.messagebox.showinfo("Sucess", "Email sent Sucessfully !")


def handle_Add():
    name_input.delete(0, END)
    course_input.delete(0, END)
    phone_input.delete(0, END)
    mail_input.delete(0, END)
    enrollment_input.delete(0, END)

def handle_Clear():
    event_input.delete(0, END)
    name_input.delete(0, END)
    course_input.delete(0, END)
    phone_input.delete(0, END)
    mail_input.delete(0, END)
    enrollment_input.delete(0, END)


# *** GUI ***

root = Tk()
#Title Name : 
root.title("ID Card Generator")
root.minsize(900, 600)

#PCU Logo : 
img = Image.open("PCU-logo.png")
resized_img = img.resize((200,100))
img = ImageTk.PhotoImage(resized_img)
img_lable = Label(root,image = img)
img_lable.pack(pady = (10, 10))

#PCU Name : 
text_lable = Label(root,text = "Pimpri Chinchwad Education Trust's", fg = "#4b4b4b")
text_lable.pack()
text_lable.config(font = ("Arial", 12))
text_lable = Label(root,text = "PIMPRI CHINCHWAD UNIVERSITY", fg = "#900C3F")
text_lable.pack()
text_lable.config(font = ("Times New Roman", 28))

#Name of the Event : 
event_lable = Label(root,text = "Enter Name of the Event ( IN UPPERCASE ONLY ) : ", fg = "#001f3e")
event_lable.pack(pady = (10, 5))
event_lable.config(font = ("Helvetica normal", 14))

event_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
event_input.pack(ipady = 4)

#Name of the Student : 
name_lable = Label(root,text = "Enter Name of the Student : ", fg = "#00386f")
name_lable.pack(pady = (10, 5))
name_lable.config(font = ("Helvetica normal", 14))

name_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
name_input.pack(ipady = 4)

#Course of the student : 
course_lable = Label(root,text = "Enter Course of the Student : ", fg = "#00386f")
course_lable.pack(pady = (10, 5))
course_lable.config(font = ("Helvetica normal", 14))

course_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
course_input.pack(ipady = 4)

#Phone Number of the Student : 
phone_lable = Label(root,text = "Enter Phone Number of the Student : ", fg = "#00386f")
phone_lable.pack(pady = (10, 5))
phone_lable.config(font = ("Helvetica normal", 14))

phone_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
phone_input.pack(ipady = 4)

#Enrollment of the Student : 
enrollment_lable = Label(root,text = "Enter Enrollment Number of the Student : ", fg = "#00386f")
enrollment_lable.pack(pady = (10, 5))
enrollment_lable.config(font = ("Helvetica normal", 14))

enrollment_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
enrollment_input.pack(ipady = 4)

#Mail of the Student : 
mail_lable = Label(root, text = "Enter Email ID of the Student : ", fg = "#00386f")
mail_lable.pack(pady = (10, 5))
mail_lable.config(font = ("Helvetica normal", 14))

mail_input = Entry(root, width = 60, bg = "#e8e8e8", font = ("Helvetica normal", 12))
mail_input.pack(ipady = 4)

 
#EXEL SHEET :
def handle_excel():
    event_name = str(event_input.get())

    File_name = (event_name + ".xlsx")
    workbook = xlsxwriter.Workbook(File_name)
    worksheet = workbook.add_worksheet()

    workbook.close()

    file_path = File_name 
    wb = load_workbook(file_path)

    ws = wb.active
    # Data to append (line by line)
    data = [
        ["NAME : " , "ENROLLMENT : ", "MAIL : ", "PHONE : ", "COURSE : ", "DATE AND TIME : "]
    ]

    # Append each row of data to the sheet
    for row in data:
        ws.append(row)

    # Save the workbook
    wb.save(file_path)
    tkinter.messagebox.showinfo("Sucess", "Excel Sheet Created Sucessfully !")


#Button : 
enter_btn = Button(root, text = "Enter", bg = "#22c857", fg = "white", font = ("Helvetica normal", 14), width = 24, height = 1, command = handle_enter)
enter_btn.place(x=800,y=650)

#Button : 
enter_btn = Button(root, text = "Add Student", bg = "#1a6bab", fg = "white", font = ("Helvetica normal", 14), width = 24, height = 1, command = handle_Add)
enter_btn.place(x=460,y=700)

#Button : 
enter_btn = Button(root, text = "Clear", bg = "#1a6bab", fg = "white", font = ("Helvetica normal", 14), width = 24, height = 1, command = handle_Clear)
enter_btn.place(x=800,y=700)

#Button : 
enter_btn = Button(root, text = "Create Excel", bg = "#1a6bab", fg = "white", font = ("Helvetica normal", 14), width = 24, height = 1, command = handle_excel)
enter_btn.place(x=460,y=650)



root.mainloop()